#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTableDataViewer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TestDatabase")]
	public partial class DataTableDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDataTable(DataTable instance);
    partial void UpdateDataTable(DataTable instance);
    partial void DeleteDataTable(DataTable instance);
    #endregion
		
		public DataTableDataClassesDataContext() : 
				base(global::DataTableDataViewer.Properties.Settings.Default.ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataTableDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataTableDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataTableDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataTableDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DataTable> DataTables
		{
			get
			{
				return this.GetTable<DataTable>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DataTable")]
	public partial class DataTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _timestamp;
		
		private string _product_name;
		
		private string _part_number;
		
		private string _camera_position;
		
		private string _camera_result;
		
		private string _product_result;
		
		private System.Nullable<float> _characteristic1;
		
		private System.Nullable<float> _characteristic2;
		
		private System.Nullable<float> _characteristic3;
		
		private System.Nullable<float> _characteristic4;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OntimestampChanging(System.DateTime value);
    partial void OntimestampChanged();
    partial void Onproduct_nameChanging(string value);
    partial void Onproduct_nameChanged();
    partial void Onpart_numberChanging(string value);
    partial void Onpart_numberChanged();
    partial void Oncamera_positionChanging(string value);
    partial void Oncamera_positionChanged();
    partial void Oncamera_resultChanging(string value);
    partial void Oncamera_resultChanged();
    partial void Onproduct_resultChanging(string value);
    partial void Onproduct_resultChanged();
    partial void Oncharacteristic1Changing(System.Nullable<float> value);
    partial void Oncharacteristic1Changed();
    partial void Oncharacteristic2Changing(System.Nullable<float> value);
    partial void Oncharacteristic2Changed();
    partial void Oncharacteristic3Changing(System.Nullable<float> value);
    partial void Oncharacteristic3Changed();
    partial void Oncharacteristic4Changing(System.Nullable<float> value);
    partial void Oncharacteristic4Changed();
    #endregion
		
		public DataTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timestamp", DbType="DateTime NOT NULL")]
		public System.DateTime timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				if ((this._timestamp != value))
				{
					this.OntimestampChanging(value);
					this.SendPropertyChanging();
					this._timestamp = value;
					this.SendPropertyChanged("timestamp");
					this.OntimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this.Onproduct_nameChanging(value);
					this.SendPropertyChanging();
					this._product_name = value;
					this.SendPropertyChanged("product_name");
					this.Onproduct_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_part_number", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string part_number
		{
			get
			{
				return this._part_number;
			}
			set
			{
				if ((this._part_number != value))
				{
					this.Onpart_numberChanging(value);
					this.SendPropertyChanging();
					this._part_number = value;
					this.SendPropertyChanged("part_number");
					this.Onpart_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_camera_position", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string camera_position
		{
			get
			{
				return this._camera_position;
			}
			set
			{
				if ((this._camera_position != value))
				{
					this.Oncamera_positionChanging(value);
					this.SendPropertyChanging();
					this._camera_position = value;
					this.SendPropertyChanged("camera_position");
					this.Oncamera_positionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_camera_result", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string camera_result
		{
			get
			{
				return this._camera_result;
			}
			set
			{
				if ((this._camera_result != value))
				{
					this.Oncamera_resultChanging(value);
					this.SendPropertyChanging();
					this._camera_result = value;
					this.SendPropertyChanged("camera_result");
					this.Oncamera_resultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_result", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string product_result
		{
			get
			{
				return this._product_result;
			}
			set
			{
				if ((this._product_result != value))
				{
					this.Onproduct_resultChanging(value);
					this.SendPropertyChanging();
					this._product_result = value;
					this.SendPropertyChanged("product_result");
					this.Onproduct_resultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_characteristic1", DbType="Real")]
		public System.Nullable<float> characteristic1
		{
			get
			{
				return this._characteristic1;
			}
			set
			{
				if ((this._characteristic1 != value))
				{
					this.Oncharacteristic1Changing(value);
					this.SendPropertyChanging();
					this._characteristic1 = value;
					this.SendPropertyChanged("characteristic1");
					this.Oncharacteristic1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_characteristic2", DbType="Real")]
		public System.Nullable<float> characteristic2
		{
			get
			{
				return this._characteristic2;
			}
			set
			{
				if ((this._characteristic2 != value))
				{
					this.Oncharacteristic2Changing(value);
					this.SendPropertyChanging();
					this._characteristic2 = value;
					this.SendPropertyChanged("characteristic2");
					this.Oncharacteristic2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_characteristic3", DbType="Real")]
		public System.Nullable<float> characteristic3
		{
			get
			{
				return this._characteristic3;
			}
			set
			{
				if ((this._characteristic3 != value))
				{
					this.Oncharacteristic3Changing(value);
					this.SendPropertyChanging();
					this._characteristic3 = value;
					this.SendPropertyChanged("characteristic3");
					this.Oncharacteristic3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_characteristic4", DbType="Real")]
		public System.Nullable<float> characteristic4
		{
			get
			{
				return this._characteristic4;
			}
			set
			{
				if ((this._characteristic4 != value))
				{
					this.Oncharacteristic4Changing(value);
					this.SendPropertyChanging();
					this._characteristic4 = value;
					this.SendPropertyChanged("characteristic4");
					this.Oncharacteristic4Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
